name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.7'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Analyze code
      run: flutter analyze

    - name: Run tests
      run: flutter test

    - name: Build for web
      run: flutter build web
  
  build_windows:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with: 
        flutter-version: 'latest'
        channel: 'stable'

    - name: Enable Windows Desktop Support
      run: flutter config --enable-windows-desktop

    - name: Install dependencies
      run: flutter pub get

    - name: Build Windows Release
      run: flutter build windows

    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: WindowsApp
        path: build/windows/runner/Release/*.exe